#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

run_regex="${MESHCLAW_ASSISTANT_E2E_RUN:-TestAssistantSignalGuardReplyRegressionMatrix|TestAssistantIndustryLatestNewsBriefPharma|TestAssistantIndustryLatestNewsBriefSemiconductor|TestAssistantIndustryNewsSkillSuggestionCreatesDraft|TestAssistantIndustryNewsReuseSuggestionShowsCard|TestAssistantIndustryNewsDoesNotHijackGenericDailyNews|TestAssistantSkillActivationToggleFlow|TestAssistantSkillTestCardFlow|TestAssistantSkillReviewReply|TestAssistantSkillReviewMissingTestReply|TestAssistantSkillRecommendationTemplateReply|TestAssistantSkillRecommendationInstalledReply|TestAssistantSkillNextTemplateReply|TestAssistantSkillNextActiveInstalledReply|TestAssistantSkillNextInactiveInstalledReply|TestAssistantSkillSearchTemplateReply|TestAssistantSkillSearchInstalledReply|TestAssistantSkillTemplateDetailReply|TestAssistantInstalledSkillDetailReply|TestAssistantSkillMarketTemplateInstallFlow|TestAssistantSkillInstallSignalApprovalFlow|TestAssistantPersonalizationStatusReplyShowsMemoryAndSkills|TestAssistantPersonalizationPreviewReplyShowsAppliedLayers|TestModelRoomReplyInjectsApprovedPersonalizationContextAndKeepsFinalApprovalBoundary|TestAssistantGenericFinalApprovalGate|TestAssistantApprovalQueueShowsPendingMailDraft|TestAssistantApprovalQueueShowsPendingMacActionReadOnly|TestAssistantApprovalQueuePendingMacActionEnglishUsesLanguagePack|TestAssistantMemorySignalApprovalFlow|TestAssistantSkillStatusReplySummarizesImplementedSkills}"

echo "==> assistant profile tests"
go test ./internal/assistantprofile -run 'TestInstallSkill|TestInspectAssistantProfileReportsReviewedSkillMarkdown|TestAddMemory|TestLoadMemoryContext|TestBuildMemorySnapshot' -count=1

echo "==> assistant Signal E2E smoke"
go test ./internal/messenger -run "$run_regex" -count=1

echo "==> assistant smoke ok"
